language: node_js
node_js:
- node
before_script:
- npm prune
script:
- npm run test
deploy:
  provider: npm
  email: mridevteam@gmail.com
  api_key:
    secure: fLDdPIfbPXjuBznQKm82LiwcQ2j/x1+sLS0VLPnDvfXsH7Oy3tlYV+zlCDTFUC/1dJXRrH+RwsrWyQTKzPkKpVKtWmYBaE13wLcT13UzpPXP3lOsgO2VuVRWipp+UZD5TL62bQtwKMqKcwy3xYWFYE97ENuJLNQN6NxscbHdDHxfb+RD+EArkvh9brSWqtInglNynW/ELG8+4mhexoI59qQVlrewM6qVasvPZtzrGrAy+d6pInlLsXkYckQWxWkN8BpvmgPEckJWKIi745ERv1OU4LB8gpy+pKO8XHVq/pQXfcb0G7w0fZaxVn06/8WoJoPE7k5FXwHZ4U8qDpwsA0bSqCPK4HKwk6dvct8IT5aqHTk6oAYAzplU3Op9PJyAxdFBGfhA8DCAk1/Qbh7kxFqkrTZFC4EiJ3jhU8hqat6xA8DaFqDGg74/t1sS+n0351AF5KFPIwvbK78dgJCuwsYwVLK3jvMQPusFlrHT0CPPymHZnhb8IURcOiLhVTISpAwDEMtuAyUHgeqK5A7gyIwoyISkOE0h4bb7jjM6d5BR/gc0T5gcwAFJfkffWdLT55YM+QRBxEalSMqaGBEvl9JA0djk+WmfPR8RK7MnqzY0RqPAj9eFsQtR46h9URq4QesvwChyDh0p2vKMtQPeXKMwcDS+D3kRyA4ZKyw/dcU=
  on:
    tags: true
    repo: mridevteam/validity_checks
